### ISSUE TITLE
KeyError:'neg_category_ids'

### ISSUE THREAD

**Issue by zhangshen12356** [JialianW/Forest_RCNN#1]
when i run the _CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/lvis/forest_rcnn_r101_32_x4d_fpn.py forest_rcnn_resnext101.pth --out out.pkl --eval bbox segm_      after loading the dataset, it occur KeyError:'neg_category_ids'       how to slove the problem

**Comment by JialianW** [comment]
I did not meet this error before. Are you using LVIS v1.0? Our code is based on LVIS v0.5.

**Comment by zhangshen12356** [comment]
> I did not meet this error before. Are you using LVIS v1.0? Our code is based on LVIS v0.5.

 I used LVIS v0.5

**Comment by zhangshen12356** [comment]
> I did not meet this error before. Are you using LVIS v1.0? Our code is based on LVIS v0.5.

Could it caused by the version of LVISAPI？beacuse the error shows in _lvis/eval.py_

**Comment by JialianW** [comment]
The LVIS API version in this repo is exactly v0.5. I can pass the test by directly using this repo and v0.5 annotations. Please kindly self-check the details in the context of your error. This error seems to be easily addressed.

**Comment by zhangshen12356** [comment]
> The LVIS API version in this repo is exactly v0.5. I can pass the test by directly using this repo and v0.5 annotations. Please kindly self-check the details in the context of your error. This error seems to be easily addressed.

ok thank you very much for your reply!

**Comment by JialianW** [comment]
In the annotation file, 'neg_category_ids' should exist in the list of 'images'.

**Comment by JialianW** [comment]
> > The LVIS API version in this repo is exactly v0.5. I can pass the test by directly using this repo and v0.5 annotations. Please kindly self-check the details in the context of your error. This error seems to be easily addressed.
> 
> ok thank you very much for your reply!

In the annotation file, 'neg_category_ids' should exist in the list of 'images'.
