### ISSUE TITLE
Enhanced C++ implementation

### ISSUE THREAD

**Issue by jesusmolrdv** [JialianW/Forest_RCNN#10]
The NMS-Resampling method is very useful and easy to understand.

However, I have found that applying the official implementation in Python (see [here](https://github.com/JialianW/Forest_RCNN/blob/b1bc0865d45caac94114064afc65bc7ee11e7d7e/mmdet/models/anchor_heads/rpn_head.py#L137)) really slows the training process.

I have managed to implement it in C++ and integrate it in mmcv, which in my case gives between **3x and 4x speed-ups** in the whole training process.

If you are interested, I can create a pull request with the code and the instructions to make use of this faster implementation. I think that this make help pepople using this useful tool.

Best regards!

**Comment by JialianW** [comment]
Thanks for your interests! Sure, it is great to integrate your better implementation into this repo if it has no compatibility issues. Thanks for your contribution! Did you integrate NMS sampling into official mmcv or mmdet repo?

**Comment by jesusmolrdv** [comment]
I have not integrated in the official repositories, but it should be something easy to do. 
Indeed, it could be interesting to try a pull request to those repositories in the future.

Regarding this repo, I would prepare a PR (inlcuding the code and instructions) in the following weeks and let you know once it's ready.

**Comment by JialianW** [comment]
Pull request merged and thus close the issue
