### ISSUE TITLE
How to generate the forest in ./kit

### ISSUE THREAD

**Issue by tonysy** [JialianW/Forest_RCNN#2]
Hi, 
thanks for your work.
Could you release the code for generating the forest npy files in ./kit, thanks in advance.

**Comment by JialianW** [comment]
Thanks for your interest in our work.

For generating the forest structure, I just wrote a simple script that performs reading the object features and running K-means. I have not cleaned up the draft code. So if you would like to use it, please drop me an email (jialianw@buffalo.edu), such that I can send you a copy of that draft.

**Comment by tonysy** [comment]
I have sent an email and thanks a lot

**Comment by tonysy** [comment]
My email is zhangsy1@shanghaitech.edu.cn, and I have sent an email, thanks a lot

**Comment by JialianW** [comment]
> My email is [zhangsy1@shanghaitech.edu.cn](mailto:zhangsy1@shanghaitech.edu.cn), and I have sent an email, thanks a lot

Sent.

**Comment by Chauncy-Cai** [comment]
For every file in kits, it consists of two lines, but it seems like the second line is never been used. I am very curious about the meaning of it. Could anyone tell me? Or just sent the code you generate these file to my email. 
My email is caishengcai@megvii.com .

**Comment by JialianW** [comment]
> For every file in kits, it consists of two lines, but it seems like the second line is never been used. I am very curious about the meaning of it. Could anyone tell me? Or just sent the code you generate these file to my email.
> My email is [caishengcai@megvii.com](mailto:caishengcai@megvii.com) .

Yes, the second column is not used. Pls just ignore it. It is actually the class id for the fine-grained class within each parent class group.

**Comment by Chauncy-Cai** [comment]
> > For every file in kits, it consists of two lines, but it seems like the second line is never been used. I am very curious about the meaning of it. Could anyone tell me? Or just sent the code you generate these file to my email.
> > My email is [caishengcai@megvii.com](mailto:caishengcai@megvii.com) .
> 
> Yes, the second column is not used. Pls just ignore it. It is actually the class id for the fine-grained class within each parent class group

I still wonder how to generate these classifications in detail, so could you send the code to my email?
thanks a lot.
