### ISSUE TITLE
poor inference mAP about bbox or segm

### ISSUE THREAD

**Issue by futureisatyourhand** [JialianW/Forest_RCNN#4]
hello,I use your model and code, the results are poor. Can you tell me why that? Thanks
![image](https://user-images.githubusercontent.com/40520052/103745114-e0cfba00-5039-11eb-9270-d457740934d8.png)

**Comment by JialianW** [comment]
> hello,I use your model and code, the results are poor. Can you tell me why that? Thanks
> ![image](https://user-images.githubusercontent.com/40520052/103745114-e0cfba00-5039-11eb-9270-d457740934d8.png)

**Comment by JialianW** [comment]
> hello,I use your model and code, the results are poor. Can you tell me why that? Thanks
> ![image](https://user-images.githubusercontent.com/40520052/103745114-e0cfba00-5039-11eb-9270-d457740934d8.png)

I git clone the code and test it again with the model released. There is no problem for me. Please check the annotations, which are lvis v0.5.

![222](https://user-images.githubusercontent.com/39213200/103815842-f6d97c80-5031-11eb-8d73-95bf8f925bad.png)

**Comment by JialianW** [comment]
@futureisatyourhand 

I git clone this repo and tested it again. There is no problem for me. Please check the annotations and make sure they are LVIS v0.5.

![222](https://user-images.githubusercontent.com/39213200/103816532-1e7d1480-5033-11eb-9b44-3e630e49f821.png)

**Comment by Never-Walk-Away** [comment]
> hello,I use your model and code, the results are poor. Can you tell me why that? Thanks ![image](https://user-images.githubusercontent.com/40520052/103745114-e0cfba00-5039-11eb-9270-d457740934d8.png)

hey! could i ask the following about your running environment? thanks!!!
